import os
import platform

import pytest

from conans.test.utils.tools import TestClient

@pytest.mark.skipif(platform.system() != "Windows", reason="Only for windows")
@pytest.mark.tool("cmake")
def test_cmake_generators_e2e_msvc():
    client = TestClient()
    
    # 1. Create dependency 'hello'
    client.run("new cmake_lib -d name=hello -d version=0.1")
    client.run("create .")
    
    # Clean the working directory for the consumer (cache remains intact)
    client.save({}, clean_first=True)
    
    # 2. Create consumer 'app' that requires 'hello'
    client.run("new cmake_exe -d name=app -d version=0.1 -d requires=hello/0.1 -f")
    
    # Modify the generated CMakeLists.txt to use conandeps.cmake
    # CMakeToolchain configures CMAKE_MODULE_PATH to include the generators folder,
    # so we can just include(conandeps)
    cmakelists = client.load("CMakeLists.txt")
    cmakelists = cmakelists.replace("find_package(hello CONFIG REQUIRED)", "include(conandeps)")
    client.save({"CMakeLists.txt": cmakelists})
    
    # Build the app using standard Conan flow which leverages CMakeToolchain/CMakeDeps
    client.run("build .")
    
    # Verify CMP0091 warning is absent (MSVC runtime policy logic)
    assert "CMAKE_POLICY_DEFAULT_CMP0091" not in client.out
    
    # Verify conandeps.cmake was actually used
    assert "Using autogenerated conandeps.cmake" in client.out

    # Verify architecture was injected into CMakePresets.json
    presets_path = None
    for root, dirs, files in os.walk(client.current_folder):
        if "CMakePresets.json" in files:
            presets_path = os.path.join(root, "CMakePresets.json")
            break
            
    assert presets_path is not None
    presets_content = client.load(presets_path)
    assert "architecture" in presets_content

