from conan.api.conan_api import ConanAPI
from conans.test.utils.tools import TestClient

def test_config_api_settings():
    client = TestClient()
    api = ConanAPI(cache_folder=client.cache_folder)
    
    # settings.yml is generated by default
    settings = api.config.settings_yml
    assert "os:" in settings
    
    # settings_user.yml does not exist by default
    settings_user = api.config.settings_user_yml
    assert settings_user == ""
    
    # create a custom settings_user.yml
    client.save({"settings_user.yml": "user:\n  settings:\n"}, path=client.cache.cache_folder)
    settings_user = api.config.settings_user_yml
    assert "user:\n  settings:\n" in settings_user

