from conan.api.conan_api import ConanAPI
from conans.test.utils.tools import TestClient

def test_config_api_settings():
    client = TestClient()
    api = ConanAPI(cache_folder=client.cache_folder)
    
    # settings.yml is generated by default
    assert "os:" in api.config.settings_yml
    
    # settings_user.yml does not exist by default
    assert api.config.settings_user_yml == ""
    
    # write custom settings.yml and settings_user.yml
    custom_settings = "os:\n  Windows:\n  Linux:\n"
    custom_settings_user = "user:\n  settings:\n"
    
    client.save({
        "settings.yml": custom_settings,
        "settings_user.yml": custom_settings_user
    }, path=client.cache.cache_folder)
    
    # Test exact string content
    assert api.config.settings_yml == custom_settings
    assert api.config.settings_user_yml == custom_settings_user
